apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gpmt-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - gympapmt.de
    - api.gympapmt.de
    secretName: gpmt-tls-secret
  rules:
  - host: gympapmt.de
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: gpmt-next
            port:
              number: 80
  - host: api.gympapmt.de
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: gpmt-api
            port:
              number: 80
