apiVersion: v1
kind: Service
metadata:
    name: mysql
spec:
    type: ExternalName
    externalName: host.minikube.internal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpmt-api
  labels:
    app: gpmt-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpmt-api
  template:
    metadata:
      labels:
        app: gpmt-api
    spec:
      containers:
      - name: gpmt-api
        image: hakrac/gpmt-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: gpmt-api
spec:
    type: NodePort
    selector:
        app: gpmt-api
    ports:
        - port: 80
          targetPort: 80
          nodePort: 30000
